// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBptoDyn3M5x2x3cJDECdsi0slPW30tOI',
    appId: '1:1063640294115:web:088a7e42add990fc135bd6',
    messagingSenderId: '1063640294115',
    projectId: 'fir-login-registration-c9b0d',
    authDomain: 'fir-login-registration-c9b0d.firebaseapp.com',
    storageBucket: 'fir-login-registration-c9b0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqkvtpRfoc0qWVOu_Gl6JVvQg7Qjx4jSs',
    appId: '1:1063640294115:android:35e5f2eb1ff4fcfa135bd6',
    messagingSenderId: '1063640294115',
    projectId: 'fir-login-registration-c9b0d',
    storageBucket: 'fir-login-registration-c9b0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAokhfj5UG_u9rqf0uP0m6O-ezWOUaERv0',
    appId: '1:1063640294115:ios:b49a139deefb3771135bd6',
    messagingSenderId: '1063640294115',
    projectId: 'fir-login-registration-c9b0d',
    storageBucket: 'fir-login-registration-c9b0d.appspot.com',
    iosClientId: '1063640294115-0g1juqi5q6tr2pf33ub6nqp97nuat4r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegistrationFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAokhfj5UG_u9rqf0uP0m6O-ezWOUaERv0',
    appId: '1:1063640294115:ios:630e6180e36071f9135bd6',
    messagingSenderId: '1063640294115',
    projectId: 'fir-login-registration-c9b0d',
    storageBucket: 'fir-login-registration-c9b0d.appspot.com',
    iosClientId: '1063640294115-fsfrpmpv2p519i93tkan465ps7osv5j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegistrationFirebaseAuth.RunnerTests',
  );
}
